spring.application.name=e-ticaret
spring.datasource.url=jdbc:postgresql://localhost:5432/eticaret
spring.datasource.username=eticaret_user
spring.datasource.password=eticaret_pass
spring.datasource.driver-class-name=org.postgresql.Driver